import Head from 'next/head'
import Image from 'next/image'
import Layout from '@/components/Layout'
import Navbar from '@/components/navbar'

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar noPicker />
      <h1>Hello</h1>
    </Layout>
  )
}
